# YOUR NAME OR TITLE OF YOUR SITE
name: KELY EUDENIA Beauty Makeup

# YOUR BRAND/PERSONAL TAGLINE
tagline: Conheça meus cursos de automaquiagem ou agende uma maquiagem comigo clicando abaixo.

# YOUR/BRAND IMAGE URL
Image_URL: https://www.kellyeudenia.com.br/assets/images/me.jpg

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://www.kellyeudenia.com.br/assets/images/background.jpg

# LOGO
logo: https://www.kellyeudenia.com.br/assets/images/logo.png

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
    
    # FACEBOOK
  - Name: Business Woman
    URL: https://www.facebook.com
    Username: harsh98trivedi
    Color: '#590219'
    Icon-Class: fab fa-facebook

    # INSTAGRAM
  - Name: ATENDIMENTO VIP MAQUIAGEM
    URL: https://www.instagram.com
    Username: harsh98trivedi
    Color: '#590219'
    Icon-Class: fab fa-instagram

    # TWITTER
  - Name: PHOTO BEATY
    URL: https://twitter.com
    Username: harsh98trivedi
    Color: '#590219'
    Icon-Class: fab fa-twitter

    # Cal.com
  - Name: MÉTODO AUTOBEATY
    URL: https://cal.com
    Username: harshtrivedi
    Color: '#590219'
    Icon-Class: fa fa-calendar-check

    # CLUBHOUSE
  - Name: CURSO VIP AUTOMAQUIAGEM
    URL: https://www.clubhouse.com
    Username: '@harsh98trivedi'
    Color: '#590219'
    Icon-Class: fas fa-hand-paper -mt-0.5

  #   # WHATSAPP
  # - Name: WhatsApp
  #   URL: https://wa.me
  #   Username: '+1123456789'
  #   Color: '#25d366'
  #   Icon-Class: fab fa-whatsapp

# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: 'No'

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
