# YOUR NAME OR TITLE OF YOUR SITE
name: KELY EUDENIA Beauty Makeup

# YOUR BRAND/PERSONAL TAGLINE
tagline: Conheça meus cursos de automaquiagem ou agende uma maquiagem comigo clicando abaixo.

# YOUR/BRAND IMAGE URL
Image_URL: https://www.kellyeudenia.com.br/assets/images/1678056741.jpg

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://www.kellyeudenia.com.br/assets/images/background.jpg

# LOGO
logo: https://www.kellyeudenia.com.br/assets/images/logo.png

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
    
    # BUSINESS WOMAN
  - Name: BUSINESS WOMAN
    Description: Lorem Ipsum is simply dummy text.
    URL: https://wa.me
    Username: '+558396004966'
    Color: '#590219'
    Icon-Class: fab fa-whatsapp

    # ATENDIMENTO VIP MAQUIAGEM
  - Name: ATENDIMENTO VIP MAQUIAGEM
    Description: Lorem Ipsum is simply dummy text.
    URL: https://wa.me
    Username: '+558396004966'
    Color: '#590219'
    Icon-Class: fab fa-whatsapp

    # PHOTO BEATY
  - Name: PHOTO BEATY
    Description: Lorem Ipsum is simply dummy text.
    URL: https://wa.me
    Username: '+558396004966'
    Color: '#590219'
    Icon-Class: fab fa-whatsapp

    # MÉTODO AUTOBEATY
  - Name: MÉTODO AUTOBEATY
    Description: Lorem Ipsum is simply dummy text.
    URL: https://wa.me
    Username: '+558396004966'
    Color: '#590219'
    Icon-Class: fab fa-whatsapp

    # CURSO VIP AUTOMAQUIAGEM
  - Name: CURSO VIP AUTOMAQUIAGEM
    Description: Lorem Ipsum is simply dummy text.
    URL: https://wa.me
    Username: '+558396004966'
    Color: '#590219'
    Icon-Class: fab fa-whatsapp

  #   # WHATSAPP
  # - Name: WhatsApp
  #   Description: Lorem Ipsum is simply dummy text. 
  #   URL: https://wa.me
  #   Username: '+1123456789'
  #   Color: '#25d366'
  #   Icon-Class: fab fa-whatsapp

# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: 'No'

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
